# Quick and dirty and relatively generic Makefile
# Generated by generate_makefile.sh
# By Joel Savitz <jsavitz@redhat.com>

CC 	= gcc
CFLAGS  = -gdwarf-4 -Wall --std=gnu11
OBJECTS = main.o sm.o dfa.o nf.o tm.o
BIN	= app

all: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) -o $(BIN)

%.tmb: %.tm.c $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) $^ -o $@

%.tm.c: %.tm
	cat $^ | ./parse.awk >> $@


%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@



.PHONEY: clean
clean:
	rm -rf $(BIN) $(OBJECTS)
