# Quick and dirty and relatively generic Makefile
# Generated by generate_makefile.sh
# By Joel Savitz <jsavitz@redhat.com>

CC 	= gcc
CFLAGS  = -gdwarf-4 -Wall --std=gnu11
OBJECTS = sm.o dfa.o nf.o tm.o
BIN	= app

all: $(BIN)

$(BIN): $(OBJECTS) main.o
	$(CC) $(CFLAGS) $^ -o $@

%.tmb: %.tm.o $(OBJECTS)
	$(CC) $(CFLAGS) $^ -o $@


%.tm.c: %.tm
	cat $^ | ./parse.awk >> $@


%.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@



.PHONEY: clean
clean:
	rm -rf $(BIN) $(OBJECTS) *.tm.c *.tmb main.o
